name: Checkbox PR Notify

on:
  pull_request:
    types: [opened, edited]

permissions: read-all|write-all

jobs:
  checkboxes-checked:
    runs-on: ubuntu-latest
    steps:
    - uses: kentaro-m/task-completed-checker-action@v0.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify when all checkboxes are ticked
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_DEST_CHAT }}
        token: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}
        disable_notification: true
        message: |
          **TEST NOTIFICATION**

          ${{ github.actor }} raised a PR.
          Repository: ${{ github.repository }}

        # All members can review here:
        # https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }}
