name: Checkbox PR Notify

on:
  pull_request:
    types: [opened, edited]
  

jobs:
  checkboxes-checked:
    runs-on: ubuntu-latest
    steps:
    # - uses: kentaro-m/task-completed-checker-action@v0.1.1
    #   with:
    #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Echo GITHUB_EVENT_PATH
      run: echo $GITHUB_EVENT_PATH
    - name: Check if checkboxes are ticked
      id: checkboxes
      run: echo ::set-output name=checked::$(grep -c "\- \[x\]" $GITHUB_EVENT_PATH)
    - name: Notify when all checkboxes are ticked
      if: ${{ steps.checkboxes.outputs.checked == '0' }}
        echo "All checkboxes are ticked. Sending notification..."
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.TELEGRAM_DEST_CHAT }}
        token: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}
        disable_notification: true
        message: |
          **TEST NOTIFICATION**

          ${{ github.actor }} raised a PR.
          Repository: ${{ github.repository }}

        # All members can review here:
        # https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }}
